### ISSUE TITLE
definition/runtime splitted component tests in studio

### ISSUE THREAD

**Issue by undx** [Talend/components#460] opened 2017-02-02 15:29 UTC
Hello,
I'm currently working on the tMarketo* components and as a best practice, I
splitted the definitions and the runtime in two separate maven project holded
by an aggregator.

Everything works fine except when _**I want to test the components in the Studio**_
(Using the NB Talend-Studio-20170131_1936-V6.4.0SNAPSHOT)...

I get the following error on Studio startup and when I drop a component from
the palette :

```
!ENTRY org.talend.platform.logging 2 0 2017-02-02 14:36:13.062
!MESSAGE 2017-02-02 14:36:13,062 WARN  org.talend.components.marketo.MarketoComponentDefinition  - getRuntimeInfo for org.talend.components.marketo.runtime.MarketoSink Dependencies: META-INF/maven/org.talend.components/marketo-runtime/dependencies.txt.

!ENTRY org.talend.platform.logging 4 0 2017-02-02 14:36:13.067
!MESSAGE 2017-02-02 14:36:13,066 ERROR org.talend.rcp.intro.ApplicationWorkbenchAdvisor  - Error while execution a login task.

!STACK 0
shaded.org.ops4j.lang.NullArgumentException: Repository spec is empty string.
	at shaded.org.ops4j.lang.NullArgumentException.validateNotEmpty(NullArgumentException.java:109)
	at org.ops4j.pax.url.mvn.internal.config.MavenRepositoryURL.<init>(MavenRepositoryURL.java:100)
	at org.ops4j.pax.url.mvn.internal.config.MavenConfigurationImpl.getRepositories(MavenConfigurationImpl.java:316)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.selectRepositories(AetherBasedResolver.java:391)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:567)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:548)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:523)
	at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:123)
	at java.net.URL.openStream(URL.java:1045)
	at org.talend.components.api.component.runtime.JarRuntimeInfo.getMavenUrlDependencies(JarRuntimeInfo.java:85)
	at org.talend.designer.core.generic.model.Component.getModulesNeeded(Component.java:1152)
	at org.talend.designer.core.generic.model.Component.getModulesNeeded(Component.java:1111)
	at org.talend.librariesmanager.model.service.LocalLibraryManager.deployComponentAndExtensionLibs(LocalLibraryManager.java:1134)
	at org.talend.librariesmanager.model.service.JavaLibrariesService.syncLibraries(JavaLibrariesService.java:227)
	at org.talend.librariesmanager.model.service.LibrariesService.syncLibraries(LibrariesService.java:128)
	at org.talend.core.CoreService.syncLibraries(CoreService.java:230)
	at org.talend.core.repository.logintask.SyncLibrariesLoginTask.run(SyncLibrariesLoginTask.java:36)
	at org.talend.rcp.intro.ApplicationWorkbenchAdvisor.preStartup(ApplicationWorkbenchAdvisor.java:116)
	at org.eclipse.ui.internal.Workbench$24.runWithException(Workbench.java:1699)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:32)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3983)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2897)
	at org.eclipse.ui.internal.Workbench.access$8(Workbench.java:2797)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:633)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.talend.rcp.intro.Application.start(Application.java:243)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

In the `configuration/config.ini` I activate my definition bundle and set the
maven repository to global.

My runtime project in deployed to my local maven repository in 
`~/.m2/repository/org/talend/components/marketo-runtime` 

I use a subclass of JarRuntimeInfo :

```java
public class MarketoRuntimeInfo extends JarRuntimeInfo {
  public static final String MAVEN_DEFINITION_ARTIFACT_ID = "marketo-definition";
  public static final String MAVEN_GROUP_ID = "org.talend.components";
  public static final String MAVEN_RUNTIME_ARTIFACT_ID = "marketo-runtime";
  public static final String MAVEN_RUNTIME_PATH = "mvn:org.talend.components/marketo-runtime";
  public static final String RUNTIME_SINK_CLASS = "org.talend.components.marketo.runtime.MarketoSink";
  public static final String RUNTIME_SOURCEORSINK_CLASS = "org.talend.components.marketo.runtime.MarketoSourceOrSink";
  public static final String RUNTIME_SOURCE_CLASS = "org.talend.components.marketo.runtime.MarketoSource";

    public MarketoRuntimeInfo(String runtimeClassName) {
        super(MAVEN_RUNTIME_PATH, DependenciesReader.computeDependenciesFilePath(MAVEN_GROUP_ID, MAVEN_RUNTIME_ARTIFACT_ID),
                runtimeClassName);
    }
}
```

Any idea for solving this problem in the Studio ?

Thanks.

**Comment by sgandon** [comment] 2017-02-06 08:26
I'll try to reproduce the pb to understand what is going on.

**Comment by sgandon** [comment] 2017-02-06 08:42
I have installed the jdbc component definition in a local TOS_DI build and I have no problems placing it on a job.
did you try to remove the _org.eclipse.*_ folders in _configuration_ ?
{code}
cd TOS_DI-20170131_1315-V6.4.0SNAPSHOT
rm -rf configuration/org.eclipse.*
{code}

Or may be can you share you components ? do you a branch where I could build them and try them out ?

**Comment by undx** [comment] 2017-02-07 09:06
Hello @sgandon,

Yes, I cleanup eclipse configuration folder before testing. I've just redone the test with the latest NB and I still have the problem.

I've justed pushed the branch feat(TDI-35436). Here is the link to the [MarketoRuntimeInfo](https://github.com/Talend/components/blob/feature/TDI-35436_Marketo/components/components-marketo/marketo-definition/src/main/java/org/talend/components/marketo/MarketoRuntimeInfo.java).

How did you installed the jdbc components in the local TOS_DI ? I maybe missed a point...

Thanks for your help !

**Comment by iistomin-gl** [comment] 2017-02-08 09:08
Hi Everyone. I have the same problem with NetSuite component with definition/runtime separation. I also tried different options (cleaning of config dirs, changing of maven config, passing of Pax URL specific system properties etc.) but with no luck.

**Comment by sgandon** [comment] 2017-02-09 11:27
I have created an TUP issue : https://jira.talendforge.org/browse/TUP-17080 because I think this is comes from some Studio configuration issue.

**Comment by iistomin-gl** [comment] 2017-03-21 08:43
I think the problem already solved so we can close this issue.

**Closed** 2017-03-23 09:21 UTC
